name: Build and Publish to Docker Hub
on:
  pull_request:
    branches:
      - main
jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: build image
        run: docker build -t tfjackc/web-apps:surveyapp-v1 .
      - name: push to docker hub
        run:
          docker login -u tfjackc -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push tfjackc/web-apps:surveyapp-v1


